spring.application.name=01_Cheav_Sarin_PP_Web_Homework002
spring.datasource.url=jdbc:postgresql://localhost:5432/my_batis_pp
spring.datasource.username=postgres
spring.datasource.password=root
mybatis.configuration.map-underscore-to-camel-case=true